spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: test
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer